import type { Metadata } from "next";
import type { MedicineDetail } from "../domain/read-models";
import { formatMedicineName } from "./format";
import { DEFAULT_LOCALE, LOCALES, localizePath, OG_LOCALES, type Locale } from "../i18n/config";
import { createT } from "../i18n/translate";
import { routes } from "./routes";
import { siteConfig } from "./site-config";

export function absoluteUrl(path: string): string {
  return new URL(path, `${siteConfig.url}/`).toString();
}

/**
 * Robots directives for a page. Pages are only indexable when the site is
 * indexable (SITE_INDEXABLE=true on production) and the page itself should be.
 */
export function pageRobots(indexablePage: boolean): Metadata["robots"] {
  return {
    index: siteConfig.indexable && indexablePage,
    follow: siteConfig.indexable,
  };
}

/** One default social image for every page (generated by app/opengraph-image.tsx). */
export const SOCIAL_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — medicines, hospitals, clinics and pharmacies in Bangladesh`,
} as const;

/** Page-level OpenGraph (Next.js replaces, not merges, the layout's openGraph object). */
export function openGraph(path: string, title: string, description: string, lang: Locale = DEFAULT_LOCALE): Metadata["openGraph"] {
  return {
    type: "website",
    siteName: siteConfig.name,
    locale: lang === DEFAULT_LOCALE ? siteConfig.locale : OG_LOCALES[lang],
    url: localizePath(path, lang),
    title,
    description,
    images: [SOCIAL_IMAGE],
  };
}

/** Twitter/X large-image card. Next.js replaces, not merges, the layout's twitter object. */
export function twitterCard(title: string, description: string): Metadata["twitter"] {
  return { card: "summary_large_image", title, description, images: [{ url: SOCIAL_IMAGE.url, alt: SOCIAL_IMAGE.alt }] };
}

export interface PageMetadataInput {
  /** Page title without the site name (the layout template appends it). */
  title: string;
  description: string;
  /** Canonical path, e.g. "/hospitals/dhaka". */
  path: string;
  /** False for thin, empty or filtered pages: noindex (still followed). */
  indexable?: boolean;
  /** Page language (default English). The canonical points at the same-language URL. */
  lang?: Locale;
}

/** Canonical + hreflang alternates for the same page in every language. */
export function languageAlternates(path: string, lang: Locale = DEFAULT_LOCALE): NonNullable<Metadata["alternates"]> {
  const languages: Record<string, string> = Object.fromEntries(LOCALES.map((l) => [l, localizePath(path, l)]));
  languages["x-default"] = path;
  return { canonical: localizePath(path, lang), languages };
}

/** Standard metadata for a page: title, description, canonical, OpenGraph and robots. */
export function pageMetadata({ title, description, path, indexable = true, lang = DEFAULT_LOCALE }: PageMetadataInput): Metadata {
  return {
    title,
    description,
    alternates: languageAlternates(path, lang),
    openGraph: openGraph(path, title, description, lang),
    twitter: twitterCard(title, description),
    robots: pageRobots(indexable),
  };
}

/** "Napa 500 mg — Medicine Information", with " & Price" only when price records exist. */
export function medicineTitle(detail: MedicineDetail, lang: Locale = DEFAULT_LOCALE): string {
  const { medicine, priceStats } = detail;
  const t = createT(lang);
  // The dosage form keeps titles unique across forms of the same brand and strength.
  return t(priceStats ? "medicine.seo.title_price" : "medicine.seo.title", {
    name: formatMedicineName(medicine),
    form: medicine.dosageFormLabel,
  });
}

export function medicineDescription(detail: MedicineDetail, lang: Locale = DEFAULT_LOCALE): string {
  const { medicine, generic, manufacturer, priceStats } = detail;
  const t = createT(lang);
  const maker = manufacturer.name.replace(/\.$/, "");
  const intro = t("medicine.seo.desc_intro", {
    name: formatMedicineName(medicine),
    form: medicine.dosageFormLabel.toLowerCase(),
    maker,
    generic: generic.name,
  });
  const count = (n: number) => n.toLocaleString("en-US");
  let rest: string;
  if (priceStats) {
    const label = t(priceStats.hasSampleData ? "medicine.seo.label_sample" : "medicine.seo.label");
    rest = t(priceStats.count === 1 ? "medicine.seo.desc_prices.one" : "medicine.seo.desc_prices.other", {
      label,
      n: count(priceStats.count),
    });
  } else if (detail.alternativesTotal > 0) {
    rest = t(detail.alternativesTotal === 1 ? "medicine.seo.desc_alts.one" : "medicine.seo.desc_alts.other", {
      n: count(detail.alternativesTotal),
    });
  } else {
    rest = t("medicine.seo.desc_forms");
  }
  return `${intro} ${rest}`;
}

// ------------------------------------------------------------ structured data

type JsonLd = Record<string, unknown>;

export interface BreadcrumbItem {
  name: string;
  /** Omit for the current page. */
  href?: string;
}

export function breadcrumbJsonLd(items: readonly BreadcrumbItem[], currentPath: string, lang: Locale = DEFAULT_LOCALE): JsonLd {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(localizePath(item.href ?? currentPath, lang)),
    })),
  };
}

/** Homepage WebSite with a sitelinks search box target (/search?q=...). */
export function websiteJsonLd(lang: Locale = DEFAULT_LOCALE): JsonLd {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteConfig.name,
    url: absoluteUrl(localizePath(routes.home(), lang)),
    inLanguage: lang,
    potentialAction: {
      "@type": "SearchAction",
      target: `${siteConfig.url}${localizePath("/search", lang)}?q={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };
}

/** Generic schema.org WebPage (used for the About page). */
export function webPageJsonLd(input: { name: string; description: string; path: string }): JsonLd {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: input.name,
    description: input.description,
    url: absoluteUrl(input.path),
    isPartOf: { "@type": "WebSite", name: siteConfig.name, url: absoluteUrl(routes.home()) },
  };
}

/**
 * schema.org Drug. Deliberately contains no offers/prices. Prescription status
 * is included only when a source publishes it.
 */
export function medicineJsonLd(detail: MedicineDetail, lang: Locale = DEFAULT_LOCALE): JsonLd {
  const { medicine, generic, manufacturer } = detail;
  return {
    "@context": "https://schema.org",
    "@type": "Drug",
    name: formatMedicineName(medicine),
    url: absoluteUrl(localizePath(routes.medicine(medicine.slug), lang)),
    ...(lang === DEFAULT_LOCALE ? {} : { inLanguage: lang }),
    description: medicine.description,
    nonProprietaryName: generic.name,
    activeIngredient: generic.name,
    dosageForm: medicine.dosageFormLabel,
    manufacturer: { "@type": "Organization", name: manufacturer.name },
    ...(medicine.prescriptionRequired === undefined
      ? {}
      : {
          prescriptionStatus: medicine.prescriptionRequired
            ? "https://schema.org/PrescriptionOnly"
            : "https://schema.org/OTC",
        }),
  };
}

/** Serialises JSON-LD for a <script> tag, escaping "<" to prevent breaking out of it. */
export function serializeJsonLd(data: JsonLd | JsonLd[]): string {
  return JSON.stringify(data).replace(/</g, "\\u003c");
}
