import type { LocalDataset } from "@/data/local/dataset";

const updatedAt = "2026-10-01T00:00:00Z";

/** Small hand-made dataset for service tests, independent of the seed files. */
export const fixtureDataset: LocalDataset = {
  generics: [
    { id: "g1", slug: "paracetamol", name: "Paracetamol" },
    { id: "g2", slug: "omeprazole", name: "Omeprazole" },
  ],
  manufacturers: [{ id: "mf1", slug: "maker", name: "Maker Ltd." }],
  medicines: [
    {
      id: "m1",
      slug: "napa-500mg",
      brandName: "Napa",
      genericId: "g1",
      manufacturerId: "mf1",
      strength: "500 mg",
      dosageForm: "tablet",
      packSize: { quantity: 10, unit: "tablets" },
      category: "Pain",
      prescriptionRequired: false,
      updatedAt,
    },
    {
      id: "m2",
      slug: "ace-500mg",
      brandName: "Ace",
      genericId: "g1",
      manufacturerId: "mf1",
      strength: "500 mg",
      dosageForm: "tablet",
      packSize: { quantity: 10, unit: "tablets" },
      category: "Pain",
      prescriptionRequired: false,
      updatedAt,
    },
    {
      id: "m3",
      slug: "napa-120mg-5ml-suspension",
      brandName: "Napa",
      genericId: "g1",
      manufacturerId: "mf1",
      strength: "120 mg/5 ml",
      dosageForm: "suspension",
      packSize: { quantity: 60, unit: "ml" },
      category: "Pain",
      prescriptionRequired: false,
      updatedAt,
    },
    {
      id: "m4",
      slug: "seclo-20mg",
      brandName: "Seclo",
      genericId: "g2",
      manufacturerId: "mf1",
      strength: "20 mg",
      dosageForm: "capsule",
      packSize: { quantity: 10, unit: "capsules" },
      category: "GI",
      prescriptionRequired: true,
      updatedAt,
    },
    {
      id: "m5",
      slug: "napadol-500mg",
      brandName: "Napadol",
      genericId: "g1",
      manufacturerId: "mf1",
      strength: "500 mg",
      dosageForm: "tablet",
      packSize: { quantity: 10, unit: "tablets" },
      category: "Pain",
      prescriptionRequired: false,
      updatedAt,
    },
  ],
  pharmacies: [
    { id: "p1", slug: "alpha-pharmacy", name: "Alpha Pharmacy", area: "Area 1", city: "Dhaka" },
    { id: "p2", slug: "beta-pharmacy", name: "Beta Pharmacy", area: "Area 2", city: "Dhaka" },
  ],
  popularMedicineIds: ["m2", "m1", "missing-id"],
  prices: [
    {
      id: "pr1",
      medicineId: "m1",
      pharmacyId: "p1",
      amount: 12,
      currency: "BDT",
      availability: "in_stock",
      source: "sample",
      updatedAt,
    },
    {
      id: "pr2",
      medicineId: "m1",
      pharmacyId: "p2",
      amount: 11.5,
      currency: "BDT",
      availability: "limited",
      source: "sample",
      updatedAt,
    },
    {
      id: "pr3",
      medicineId: "m2",
      pharmacyId: "p1",
      amount: 12,
      currency: "BDT",
      availability: "in_stock",
      source: "sample",
      updatedAt,
    },
  ],
};
